"""initial

Revision ID: 945ab166682b
Revises: 
Create Date: 2026-03-07 16:29:05.419693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945ab166682b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('product_data', sa.JSON(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_descriptions_category'), 'generated_descriptions', ['category'], unique=False)
    op.create_index(op.f('ix_generated_descriptions_id'), 'generated_descriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_descriptions_id'), table_name='generated_descriptions')
    op.drop_index(op.f('ix_generated_descriptions_category'), table_name='generated_descriptions')
    op.drop_table('generated_descriptions')
    # ### end Alembic commands ###
